name: Matari Agro Indonesia, Konsultan dan Pusat Pelatihan Pertanian
markdown: kramdown
permalink: /articles/:title
#permalink: /blog/:year/:month/:day/:title

plugins: ["jekyll-paginate", "jekyll-multiple-languages-plugin"]

# Paginate
paginate: 12
paginate_path: "/articles/page:num/"


# jekyll-multiple-languages-plugin settings:
languages: ["id", "en"]

exclude_from_localizations: ["javascript", "img", "images", "css", "scripts", "favicon.ico"]
